#!/usr/bin/env python3
"""Static checks for the BGET site — standard library only, no dependencies.

Run from anywhere:  python3 tests/static_check.py

Checks (per page: index.html, apply.html, manifesto.html):
  (a) HTML tag balance, duplicate ids, exactly one <h1>
  (b) every href="#..." resolves to an id on the same page
  (c) every relative href/src resolves to a file on disk
  (d) cross-page links (page.html / page.html#anchor) resolve
  (e) no root-absolute paths like src="/foo"
  (f) the four SHARED:HEADER/FOOTER markers present, balanced, in order

manifesto.html is treated as optional: if it does not exist yet the checks
for it are skipped with a warning (it is generated by build-manifesto.py).

Exit status: 0 when there are no errors, 1 otherwise.
Warnings never fail the run.
"""

from __future__ import annotations

import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Pages that must exist.  manifesto.html is optional (generated concurrently).
REQUIRED_PAGES = ["index.html", "apply.html"]
OPTIONAL_PAGES = ["manifesto.html"]

VOID_ELEMENTS = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}

# Elements that implicitly close an open <p>.
_P_CLOSERS = {
    "address", "article", "aside", "blockquote", "details", "div", "dl",
    "fieldset", "figcaption", "figure", "footer", "form", "h1", "h2", "h3",
    "h4", "h5", "h6", "header", "hr", "main", "menu", "nav", "ol", "p",
    "pre", "section", "table", "ul",
}

# Implicit end-tag rules: while the top of the stack is in this list, pop it.
_IMPLICIT = {
    "li": ("li",),
    "dt": ("dt", "dd"),
    "dd": ("dt", "dd"),
    "option": ("option",),
    "optgroup": ("optgroup", "option"),
    "tr": ("tr", "td", "th", "thead", "tbody", "tfoot"),
    "td": ("td", "th"),
    "th": ("td", "th"),
    "thead": ("thead", "tbody", "tfoot"),
    "tbody": ("thead", "tbody", "tfoot"),
    "tfoot": ("thead", "tbody", "tfoot"),
    "colgroup": ("colgroup",),
}

EXTERNAL_SCHEME_PREFIXES = ("http:", "https:", "mailto:", "tel:", "data:",
                            "javascript:", "ftp:", "sms:", "geo:")

SHARED_MARKERS = [
    "<!-- SHARED:HEADER:START -->",
    "<!-- SHARED:HEADER:END -->",
    "<!-- SHARED:FOOTER:START -->",
    "<!-- SHARED:FOOTER:END -->",
]


class PageParse(HTMLParser):
    """Single pass over an HTML file collecting everything the checks need."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.stack: list[str] = []
        self.balance_errors: list[str] = []   # "line N: message"
        self.ids: list[tuple[str, int]] = []  # (id value, line)
        self.refs: list[tuple[str, str, int]] = []  # (attr, value, line)
        self.h1_count = 0
        self.tag_counts: dict[str, int] = {}

    # -- helpers ---------------------------------------------------------
    def _line(self) -> int:
        return self.getpos()[0]

    def _close_implicit(self, tag: str) -> None:
        while self.stack and self.stack[-1] in _IMPLICIT.get(tag, ()):
            self.stack.pop()
        # <p> is closed by block-level start tags and by </p>'s friends.
        if tag in _P_CLOSERS:
            while self.stack and self.stack[-1] == "p":
                self.stack.pop()

    # -- events ----------------------------------------------------------
    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        line = self._line()
        self.tag_counts[tag] = self.tag_counts.get(tag, 0) + 1
        adict = {k: (v if v is not None else "") for k, v in attrs}
        if "id" in adict and adict["id"]:
            self.ids.append((adict["id"], line))
        for attr in ("href", "src"):
            if attr in adict:
                self.refs.append((attr, adict[attr], line))
        if tag == "h1":
            self.h1_count += 1
        if tag in VOID_ELEMENTS:
            return
        self._close_implicit(tag)
        self.stack.append(tag)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        # Self-closing form: counts for ids/refs but never enters the stack.
        line = self._line()
        adict = {k: (v if v is not None else "") for k, v in attrs}
        if "id" in adict and adict["id"]:
            self.ids.append((adict["id"], line))
        for attr in ("href", "src"):
            if attr in adict:
                self.refs.append((attr, adict[attr], line))
        if tag == "h1":
            self.h1_count += 1

    def handle_endtag(self, tag: str) -> None:
        if tag in VOID_ELEMENTS:
            return
        line = self._line()
        if not self.stack:
            self.balance_errors.append(f"line {line}: stray </{tag}> with no open element")
            return
        if self.stack[-1] == tag:
            self.stack.pop()
            return
        if tag in self.stack:
            while self.stack and self.stack[-1] != tag:
                self.balance_errors.append(
                    f"line {line}: </{tag}> closes over unclosed <{self.stack[-1]}>"
                )
                self.stack.pop()
            self.stack.pop()
        else:
            self.balance_errors.append(f"line {line}: stray </{tag}> (never opened)")


class Checker:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []
        self._warned: set[str] = set()
        self.pages: dict[str, PageParse] = {}

    def error(self, msg: str) -> None:
        self.errors.append(msg)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)

    def warn_once(self, key: str, msg: str) -> None:
        """Emit a warning only the first time `key` is seen (keeps output tidy)."""
        if key in self._warned:
            return
        self._warned.add(key)
        self.warnings.append(msg)

    # -- loading ---------------------------------------------------------
    def load(self, name: str) -> PageParse | None:
        path = ROOT / name
        if not path.is_file():
            if name in OPTIONAL_PAGES:
                self.warn(f"{name}: not found — skipping its checks "
                          "(generated separately; it may not have landed yet)")
            else:
                self.error(f"{name}: required page is missing")
            return None
        parser = PageParse()
        try:
            parser.feed(path.read_text(encoding="utf-8"))
            parser.close()
        except Exception as exc:  # pragma: no cover - malformed input
            self.error(f"{name}: failed to parse ({exc})")
            return None
        self.pages[name] = parser
        return parser

    # -- checks ----------------------------------------------------------
    def check_balance(self, name: str, p: PageParse) -> list[str]:
        out = [f"{name}: {e}" for e in p.balance_errors]
        for msg in list(out):
            self.error(msg)
        if p.stack:
            msg = f"{name}: unclosed elements at end of file: {', '.join('<' + t + '>' for t in p.stack)}"
            out.append(msg)
            self.error(msg)
        return out

    def check_ids_and_h1(self, name: str, p: PageParse) -> list[str]:
        out: list[str] = []
        seen: dict[str, int] = {}
        for value, line in p.ids:
            if value in seen:
                msg = f"{name}: line {line}: duplicate id \"{value}\" (first at line {seen[value]})"
                out.append(msg)
                self.error(msg)
            else:
                seen[value] = line
        if p.h1_count != 1:
            msg = f"{name}: expected exactly one <h1>, found {p.h1_count}"
            out.append(msg)
            self.error(msg)
        return out

    @staticmethod
    def _split_ref(value: str) -> tuple[str, str]:
        """'page.html#a?x' -> ('page.html', 'a')  (query strings dropped)."""
        frag = ""
        path = value
        if "#" in path:
            path, frag = path.split("#", 1)
        if "?" in path:
            path = path.split("?", 1)[0]
        if "?" in frag:
            frag = frag.split("?", 1)[0]
        return path, frag

    def check_refs(self, name: str, p: PageParse) -> list[str]:
        """Checks (b), (c), (d) and (e) for one page."""
        out: list[str] = []
        id_set = {v for v, _ in p.ids}

        for attr, value, line in p.refs:
            value = value.strip()
            if not value:
                continue
            low = value.lower()

            # (b) same-page anchor
            if value.startswith("#"):
                frag = value[1:]
                if frag and frag not in id_set:
                    msg = (f"{name}: line {line}: {attr}=\"{value}\" — "
                           f"no id=\"{frag}\" on this page")
                    out.append(msg)
                    self.error(msg)
                continue

            # (e) root-absolute path
            if value.startswith("/"):
                msg = (f"{name}: line {line}: {attr}=\"{value}\" — root-absolute "
                       f"path (use a relative path)")
                out.append(msg)
                self.error(msg)
                continue

            # external / special schemes (http, https, mailto, tel, data, //host)
            if low.startswith(EXTERNAL_SCHEME_PREFIXES) or value.startswith("//"):
                continue

            path, frag = self._split_ref(value)
            if not path:
                continue  # e.g. "?query" only

            target = (ROOT / path) if not path.startswith("..") else (ROOT / name).parent / path
            # resolve relative to the page's own directory (all pages live at root)
            target = target.resolve()
            try:
                target.relative_to(ROOT.resolve())
            except ValueError:
                msg = f"{name}: line {line}: {attr}=\"{value}\" — escapes the project root"
                out.append(msg)
                self.error(msg)
                continue

            # (c) file on disk
            if not target.is_file():
                rel = target.relative_to(ROOT.resolve()) if target.is_relative_to(ROOT.resolve()) else target
                if name in OPTIONAL_PAGES or str(rel) in OPTIONAL_PAGES:
                    self.warn_once(
                        f"missing:{name}:{value}",
                        f"{name}: {attr}=\"{value}\" points at optional page {rel}, "
                        f"which does not exist yet (further references not listed)",
                    )
                else:
                    msg = f"{name}: line {line}: {attr}=\"{value}\" — file not found: {rel}"
                    out.append(msg)
                    self.error(msg)
                continue

            # (d) cross-page anchor
            if frag and target.suffix == ".html":
                rel = str(target.relative_to(ROOT.resolve()))
                if rel in self.pages:
                    target_ids = {v for v, _ in self.pages[rel].ids}
                else:
                    if rel in OPTIONAL_PAGES:
                        self.warn_once(
                            f"frag:{name}:{value}",
                            f"{name}: {attr}=\"{value}\" — cannot verify #{frag}: "
                            f"{rel} not present yet",
                        )
                        continue
                    target_parser = PageParse()
                    target_parser.feed(target.read_text(encoding="utf-8"))
                    target_parser.close()
                    self.pages[rel] = target_parser
                    target_ids = {v for v, _ in target_parser.ids}
                if frag not in target_ids:
                    msg = (f"{name}: line {line}: {attr}=\"{value}\" — "
                           f"{rel} has no id=\"{frag}\"")
                    out.append(msg)
                    self.error(msg)
        return out

    def check_markers(self, name: str) -> list[str]:
        out: list[str] = []
        path = ROOT / name
        text = path.read_text(encoding="utf-8")
        positions: list[int] = []
        for marker in SHARED_MARKERS:
            count = text.count(marker)
            if count == 0:
                msg = f"{name}: missing shared-chrome marker {marker}"
                out.append(msg)
                self.error(msg)
                positions.append(-1)
            elif count > 1:
                msg = f"{name}: marker {marker} appears {count} times (expected 1)"
                out.append(msg)
                self.error(msg)
                positions.append(text.index(marker))
            else:
                positions.append(text.index(marker))
        # START/END balance + order (HEADER pair must precede FOOTER pair)
        if positions[0] >= 0 and positions[1] >= 0 and positions[0] > positions[1]:
            msg = f"{name}: SHARED:HEADER:START appears after SHARED:HEADER:END"
            out.append(msg)
            self.error(msg)
        if positions[2] >= 0 and positions[3] >= 0 and positions[2] > positions[3]:
            msg = f"{name}: SHARED:FOOTER:START appears after SHARED:FOOTER:END"
            out.append(msg)
            self.error(msg)
        if positions[1] >= 0 and positions[2] >= 0 and positions[1] > positions[2]:
            msg = f"{name}: HEADER block appears after FOOTER block"
            out.append(msg)
            self.error(msg)
        return out


def main() -> int:
    print("BGET static check")
    print("=" * 60)

    checker = Checker()
    page_names = list(REQUIRED_PAGES) + list(OPTIONAL_PAGES)

    # Load every existing page first so cross-page checks can read ids.
    loaded: dict[str, PageParse] = {}
    for name in page_names:
        parser = checker.load(name)
        if parser is not None:
            loaded[name] = parser

    check_results: list[tuple[str, str, bool, int]] = []

    def record(label: str, findings: list[str]) -> None:
        check_results.append((label, "FAIL" if findings else "PASS", not findings, len(findings)))

    for name, parser in loaded.items():
        record(f"(a) tag balance — {name}", checker.check_balance(name, parser))
        record(f"(a) ids + <h1> — {name}", checker.check_ids_and_h1(name, parser))
        record(f"(b,c,d,e) links — {name}", checker.check_refs(name, parser))
        record(f"(f) shared markers — {name}", checker.check_markers(name))

    # De-duplicate any findings recorded twice (record() is per page; errors
    # were appended once each) and print the per-check table.
    print()
    for label, status, _, count in check_results:
        mark = "PASS" if status == "PASS" else "FAIL"
        extra = f" ({count} finding{'s' if count != 1 else ''})" if count else ""
        print(f"  [{mark}] {label}{extra}")

    if checker.warnings:
        print("\nWarnings:")
        for w in checker.warnings:
            print(f"  ! {w}")

    if checker.errors:
        print("\nErrors:")
        for e in checker.errors:
            print(f"  x {e}")
        print(f"\nRESULT: FAIL — {len(checker.errors)} error(s), "
              f"{len(checker.warnings)} warning(s)")
        return 1

    print(f"\nRESULT: PASS ({len(checker.warnings)} warning(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
