#!/usr/bin/env python3
"""Sync the shared chrome (announcement + header + drawer, footer) across pages.

The canonical source of truth is index.html, which wraps the shared blocks in
markers:

    <!-- SHARED:HEADER:START --> ... <!-- SHARED:HEADER:END -->
    <!-- SHARED:FOOTER:START --> ... <!-- SHARED:FOOTER:END -->

This script copies those blocks into the other pages and re-applies the two
per-page adaptations:

  1. Homepage section anchors (#vision, #people, ...) become index.html#...
     so they resolve on pages where those ids do not exist.
  2. Links pointing at the page itself get aria-current="page".

manifesto.html is generated by build-manifesto.py, which performs the same
adaptation when it extracts the chrome from index.html — re-running the
generator is equivalent to syncing that page.

Usage:
    python3 tools/sync_chrome.py          # sync, printing a summary
    python3 tools/sync_chrome.py --check  # exit 1 if anything would change

The repository's static check (tests/static_check.py) verifies that the
markers exist, are balanced and in order on every page.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = "index.html"
TARGETS = ["apply.html", "manifesto.html"]

# Anchors that only exist on the homepage.
HOMEPAGE_ANCHORS = r"#(vision|people|character|how|labs|north-star)"

BLOCKS = ["HEADER", "FOOTER"]


def extract_block(text: str, name: str) -> tuple[int, int]:
    start = f"<!-- SHARED:{name}:START -->"
    end = f"<!-- SHARED:{name}:END -->"
    i = text.index(start)
    j = text.index(end) + len(end)
    return i, j


def adapt(block: str, page: str) -> str:
    if page != SOURCE:
        block = re.sub(
            rf'href="{HOMEPAGE_ANCHORS}"', r'href="index.html#\1"', block
        )
        block = re.sub(
            rf'(<a href="{re.escape(page)}")(?=[\s>])',
            r'\1 aria-current="page"',
            block,
        )
        # Idempotency guard in case the source already carried the attribute.
        block = block.replace('aria-current="page" aria-current="page"', 'aria-current="page"')
    return block


def main() -> int:
    check_only = "--check" in sys.argv
    source_text = (ROOT / SOURCE).read_text(encoding="utf-8")
    source_blocks = {
        name: source_text[slice(*extract_block(source_text, name))]
        for name in BLOCKS
    }

    changed: list[str] = []
    for page in TARGETS:
        path = ROOT / page
        if not path.exists():
            print(f"  ! {page}: not found, skipping")
            continue
        text = original = path.read_text(encoding="utf-8")
        for name in BLOCKS:
            i, j = extract_block(text, name)
            text = text[:i] + adapt(source_blocks[name], page) + text[j:]
        if text != original:
            changed.append(page)
            if not check_only:
                path.write_text(text, encoding="utf-8")

    if check_only:
        if changed:
            print(f"Chrome out of sync in: {', '.join(changed)}")
            return 1
        print("Chrome in sync.")
        return 0

    if changed:
        print(f"Synced chrome in: {', '.join(changed)}")
    else:
        print("Chrome already in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
